# Generated by Django 5.1.4 on 2024-12-11 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Type your comment'),
        ),
        migrations.AddField(
            model_name='memory',
            name='description',
            field=models.TextField(default='Tell your story'),
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.relative'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
