# Generated by Django 5.1.4 on 2024-12-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_text_memory_description_memory_memory_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.memory'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Type your comment'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.relative'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(),
        ),
    ]
